### ISSUE TITLE
FNP not calculating properly with multiple weapons 

### ISSUE THREAD

**Issue by KarnivoreBug** [dixhuit/unitcrunch-issue-tracker#103]
### Debug data
Submitted debug via the URL, will refer to those weapons. 

### Describe the bug
Feel no pain/damage ignored number drastically changing as weapons are added, only providing accurate number with single weapon selected.
Specifically the 9.1 estimated damage of the karnivore being reduced to 4.2 'damage not ignored' from a 5+ fnp (expected output ~6 damage)

### To Reproduce
1. Select 4 weapons (Stalker Claw, Stalker Melta, Thermal Spear Brigand, Karnivore Claw)
2. Change Defender to 'Norn', stats t11, 16w, 3+ sv, 4+ inv, 5+ FNP

### Expected behavior
Expected FNP to reduce damage by 33%. Reduced karnivore claw below half damage. 

### Screenshots
https://i.imgur.com/MnURLzY.png - results
https://i.imgur.com/IHesFPO.png - weapon profiles
https://i.imgur.com/gRf02kZ.png - defender profile, global mods (all off, obviously)

**Comment by dixhuit** [comment]
Thanks for this, will investigate ASAP.

**Comment by dixhuit** [comment]
I don't think this is a bug - more of a misinterpretation of the results (and its a weird one, so this is totally understandable).

Since UC 0.64 and the introduction of the possibility of multi-model type profiles, UC has had to change in a few ways, most notably:

1. The attack sequence is "slow rolled" (very quickly), meaning that each attack is fully resolved, and the outcomes of the resolved attack are assessed, before moving on to the next attack. UC did this a fair bit before v0.64, now it does it more strictly. This is due to the need to know when to allocate an attack to a new defender model type because the current model type is now slain. 
2. UC no longer calculates & displays "overkill" because defender profiles may contain multiple model type defender stats.

As such, in the case of multi-weapon attackers vs a defender with a FNP, it's entirely possible for earlier weapons in the attacker's list of selected weapons to slay the defender before the later weapons get a look-in (when it comes to "damage not ignored"). All selected weapons will still fire and their results should be fairly consistent all the way up to "damage dealt", but if the defender is already slain by the time we get to calculating the "damage not ignored" then the attack will just be dropped (instead of calculating theoretical-only overkill "damage not ignored") - resulting in lower than expected values for later weapon "damage not ignored" results, given that same weapon's "damage dealt" result.

Your shared scenario is particularly susceptible to this as all of the weapons involved hit pretty hard and are pretty swingy. You can recreate what I'm trying to explain with different selected weapons (including less swingy ones), so long as the earlier weapons in the list of selected weapons have a chance to slay the defender before we get to using the later/last weapon(s). The greater the chance of slaying the defender early like this, the greater the impact it'll have on the later weapons.
